### ISSUE TITLE
More clearly explain Draftail's relationship with Draft.js and Wagtail

### ISSUE THREAD

**Issue by alexgleason** [thibaudcolas/draftail.org#14]
springload/draftail#167 reproduced here:

> Being a newbie to Draft.js and Draftail, I'm curious:
> 
> 1. What are the differences between Draft.js and Draftail?
> 2. What is Draftail's scope? eg, is it a standalone alternative to Draft.js, or does it only make sense to use within Wagtail?
> 3. Why did the Wagtail team decide to use a fork?
> 
> I checked the readme and the website and felt this wasn't clear. As an outsider trying to learn/understand Draftail, these are some of the first things I'd want to know to help me understand the project.
> 
> Thanks!

I'm thinking this would be helpful either on the homepage or as the landing page of the docs.

**Comment by thibaudcolas** [comment]
👋 good point, I think this would be worth addressing better in both the README and the homepage (or one of the first pages in the docs section). There is https://www.draftail.org/blog/2018/03/05/why-wagtail-new-editor-is-built-with-draft-js, but it's not easily accessible.

In short, Draftail isn't a fork of Draft.js. Draft.js is a framework to build rich text editors, basically making React components usable within `contenteditable` HTML, and providing a model and API for rich text content & operations.

Draftail is a standalone editor, so should be usable anywhere a rich text editor is needed with or without Wagtail. Its built-in functionality is quite limited (not much built-in UI beyond the toolbar and editor area) so it can be better integrated into other systems, like Wagtail's configurable rich text features. Its stated goals are to be 1. easy to use 2. bulletproof to as much rich text abuse as possible 3. highly customisable.

The one thing Draftail doesn't have on its own is the ability to output HTML (as it [stores content in its own format](https://www.draftail.org/docs/content-storage). Within Wagtail, that's provided by https://github.com/springload/draftjs_exporter, which can also be used standalone. When it's desirable to keep all of this rich text processing in JS land, there is https://www.draftail.org/docs/importing-and-exporting-html which covers using https://github.com/HubSpot/draft-convert as a converter for Draft.js content.

**Comment by thibaudcolas** [comment]
I have updated the homepage with a different tagline for the project, and more details about the editor. The "getting started" docs also make it clear that Draft.js is a separate dependency.
